import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@repo/ui/styles.css";
import { Footer } from "@repo/ui/footer";
import React from "react";
import UserAppBar from "../components/userAppBar";
import { Provider } from "./lib/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode,
}>) {
  return (

    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen overflow-auto overflow-x-hidden relative `}>
        <Provider>
          <UserAppBar/>
          {children}
          <Footer />
        </Provider>
      </body>
    </html>


  );
}
