import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@repo/ui/styles.css";
import { Appbar } from "../components/appbar";
import { Footer } from "@repo/ui/footer";
import {Providers} from "../provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
 
}>) {
  return (
    
        <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen overflow-auto overflow-x-hidden relative `}>
      <Providers>
            <Appbar/>
            {children}
            <Footer/>
      </Providers>
      </body>
    </html>
    
    
  );
}
